# Generated by Django 3.0 on 2020-01-07 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_b', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
                ('teacher_id', models.OneToOneField(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='app_b.Teacher')),
            ],
        ),
    ]
