# Generated by Django 3.0 on 2020-01-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_b', '0002_teacherdetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacherdetail',
            table='t_teacher_detail',
        ),
    ]
